"""Add Tag and TagGroup.

Revision ID: 82abb4ac5b10
Revises: 87d85bd683da
Create Date: 2024-01-09 18:19:37.596204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82abb4ac5b10'
down_revision = '87d85bd683da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('tag_groups')
    # ### end Alembic commands ###
